import type { Metadata } from "next";
import { Inter, Jost, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/layouts/Header/Header";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({
  weight: ["500"], 
  subsets: ["latin"],
  variable: "--font-jost",
  display: "swap",
});
const notoSansJP = Noto_Sans_JP({
  weight: ["500", "700"],
  subsets: ["latin"],
  variable: "--font-notoSansJP",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} ${jost.variable} ${notoSansJP.variable}`}>
        <Header />
        <main className="pt-[80px]">
          {children}
        </main>
      </body>
    </html>
  );
}

//layout.tsxのchildrenをmainタグでくくってヘッダーとの位置調整を行いました
