import type { Metadata } from "next";
import { Inter, Jost, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header/Header";
import Footer from "@/components/layouts/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-notoSansJP",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} ${jost.variable} ${notoSansJP.variable}`}>
        <Header />
        <main className="pt-[80px] bg-secondary-100">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
